# Generated by Django 3.2.5 on 2022-01-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_like_like_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendsmanager',
            unique_together={('current', 'friend_requests')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'user')},
        ),
    ]
